services:
  api:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy  
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: wound_analyzer-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wound_user
      POSTGRES_DB: wound_analyzer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:
